# Generated by Django 4.2.1 on 2023-06-13 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=225, verbose_name='Ism Familiya')),
                ('course', models.CharField(choices=[('Ingliz tili', 'Ingliz tili'), ('Rus tili', 'Rus tili'), ('Arab tili', 'Arab tili'), ('Koreys tili', 'Koreys tili')], max_length=255)),
                ('phone', models.CharField(max_length=225, verbose_name='Telefon raqami')),
                ('experience', models.CharField(max_length=225, verbose_name='tajribasi')),
                ('img', models.ImageField(upload_to='Teacher_img', verbose_name="O'qituvchining rasmi")),
            ],
            options={
                'verbose_name': "O'qituvchi",
                'verbose_name_plural': "O'qituvchilar",
            },
        ),
    ]
