# Generated by Django 4.2.1 on 2023-06-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='img',
            field=models.ImageField(upload_to='', verbose_name="O'qituvchining rasmi"),
        ),
    ]
