# Generated by Django 4.2.1 on 2023-06-13 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='markaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('Ingliz tili', 'Ingliz tili'), ('koreys tili', 'koreys tili'), ('rus tili', 'rust tili'), ('arab tili', 'arab tili'), ('mental arifmetika', 'mental arifmetika'), ('matematika', 'matematika')], max_length=225)),
                ('price', models.CharField(max_length=225, null=True, verbose_name='narxi')),
                ('oyi', models.CharField(max_length=225, null=True, verbose_name='Kurs davomiyligi')),
            ],
        ),
    ]
