# Generated by Django 4.2.1 on 2023-06-13 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon_nomer', models.CharField(max_length=225, verbose_name='Telefon nomer')),
                ('surname', models.CharField(max_length=225, verbose_name='ism , familiya')),
                ('teacher', models.CharField(max_length=225, verbose_name="O'qituvchi")),
                ('number', models.CharField(max_length=225, verbose_name='Telefon nomer')),
                ('message', models.TextField(blank=True, default="Siz 4K english academyda ro'yxatdan o'ydingiz", verbose_name="Boshqa ma'lumotlar")),
            ],
        ),
    ]
