# Generated by Django 4.2.1 on 2023-06-13 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='telefon_nomer',
        ),
        migrations.AddField(
            model_name='user',
            name='yoshi',
            field=models.CharField(max_length=225, null=True, verbose_name="O'qituvchining yoshi"),
        ),
        migrations.AlterField(
            model_name='user',
            name='message',
            field=models.TextField(blank=True, default="Siz 4K english academyda ro'yxatdan o'tdingiz", verbose_name="Boshqa ma'lumotlar"),
        ),
    ]
